Page:
  resource: "@BloggerBlogBundle/Controller/PageController.php"
  type:     annotation
  prefix:   /

Blog:
  resource: "@BloggerBlogBundle/Controller/BlogController.php"
  type:     annotation
  prefix:   /blog

Comment:
  resource: "@BloggerBlogBundle/Controller/CommentController.php"
  type:     annotation
  prefix:   /comment